export const customers = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        current_page: 1,
        data: [
            {
                id: 0,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "string",
                status: "publish",
                zone: "string",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 1,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "string",
                status: "publish",
                zone: "string",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 3,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "string",
                status: "publish",
                zone: "string",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 4,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "string",
                status: "publish",
                zone: "string",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
        ],
        first_page_url: "string",
        from: 0,
        last_page: 4,
        last_page_url: "string",
        links: [
            {
                url: "string",
                label: "string",
                active: "true",
            },
        ],
        next_page_url: "string",
        path: "string",
        per_page: 1,
        prev_page_url: "string",
        to: 25,
        total: 100,
    },
};

export const customer_detail = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        id: 2,
        uuid: "99efcc08-623e-ea80-847b-46c0805ac6d7",
        cid: "jYDUZqSzE3",
        display_name: "Chic Suk Yee",
        email: "chicsy@gmail.com",
        phone: "74-839-6185",
        type: "2xKbSUM05T",
        created_at: null,
        updated_at: 1695636583,
        contact_id: 2,
        gender: "admin",
        address: "402 Nguyễn Thị Minh Khai",
        company: "Adsplus",
        tax_code: "030406",
        fax: "215",
        bio: null,
        job_title: "Senior Intern",
        zone: "TPHCM",
        specialization: "admin",
        avatar_url: "",
    },
};

export const customer_courses = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: [
        {
            id: 1,
            uuid: "3254259a-6fe0-6919-d7c9-b7b43022ccb2",
            course_category_id: 6,
            name: "Nakajima Riku",
            method: "qSvQz9Vlvv",
            original_price: "480.77",
            discounted_price: "922.96",
            sale_price: "495.01",
            unit: "NVWygbX9jF",
            capacity: 8,
            enrollment: 190,
            start_date: 1002444834,
            end_date: 1364477976,
            start_time: 1695700547,
            end_time: 1695708690,
            level: "yJWlPcm2px",
            zone: "LDqSCiCpIY",
            code: "Swf0MWyljd",
            status: "bIOQRceNLe",
            stage: "WujDxdAOKh",
            description: null,
            created_at: 1134383506,
            updated_at: 1315010400,
            deleted_at: null,
            type: "google-ads",
        },
    ],
};

export const customer_lessions = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: [
        {
            id: 1,
            uuid: "2e1b92ba-87f3-66c6-4742-dec2e36f1913",
            course_id: 1,
            instructor_id: 11,
            topic_id: 1,
            status: "Q8PXrA6GLf",
            start_date: 1695869475000,
            end_date: 1695869475000,
            created_at: 1619552056,
            updated_at: 1220753641,
            name: "Debra Wagner",
            instructor: {
                display_name: "Andrew Mitchell",
                email: "andrmitc@gmail.com",
                phone: "7230 449434",
            },
            topic: {
                name: "TESTING",
                theory_percent: 10,
                practice_percent: 10,
                actual_share_percent: 80,
            },
            course: {
                name: "Nakajima Riku",
            },
        },
        {
            id: 2,
            uuid: "2e1b92ba-87f3-66c6-4742-dec2e36f1913",
            course_id: 1,
            instructor_id: 12,
            topic_id: 1,
            status: "Q8PXrA6GLf",
            start_date: 1695869475000,
            end_date: 1695869475000,
            created_at: 1619552056,
            updated_at: 1220753641,
            name: "Debra Wagner",
            instructor: {
                display_name: "Andrew Mitchell",
                email: "andrmitc@gmail.com",
                phone: "7230 449434",
            },
            topic: {
                name: "TESTING",
                theory_percent: 10,
                practice_percent: 10,
                actual_share_percent: 80,
            },
            course: {
                name: "Nakajima Riku",
            },
        },
    ],
};

export const customer_invoices = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        current_page: 1,
        data: [
            // {
            //     id: 1,
            //     date: 1694921574000,
            //     amount: 100000000,
            //     status: "paid",
            //     course: "Google Ads",
            //     payment_type: "card",
            // },
            // {
            //     id: 1,
            //     date: 1694967066000,
            //     amount: 100000000,
            //     status: "paid",
            //     course: "Facebook Ads",
            //     payment_type: "cash",
            // },
        ],
        first_page_url: "string",
        from: 0,
        last_page: 4,
        last_page_url: "string",
        links: [
            {
                url: "string",
                label: "string",
                active: "true",
            },
        ],
        next_page_url: "string",
        path: "string",
        per_page: 1,
        prev_page_url: "string",
        to: 25,
        total: 100,
    },
};

export const customer_statistics = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        total: 2,
        total_facebook: 1,
        total_google: 1,
    },
};
