export default {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        current_page: 1,
        data: [
            {
                id: 0,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "google-ads",
                status: "publish",
                zone: "hcm",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 45,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "facebook-ads",
                status: "pending",
                zone: "hn",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 90,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "google-ads",
                status: "pending",
                zone: "hn",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 234,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "facebook-ads",
                status: "pending",
                zone: "hn",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 245,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "google-ads",
                status: "pending",
                zone: "hcm",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 57582,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "google-ads",
                status: "pending",
                zone: "hcm",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 67892,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "facebook-ads",
                status: "pending",
                zone: "hcm",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
            {
                id: 89762,
                uuid: "string",
                cid: "string",
                display_name: "string",
                phone: "string",
                email: "string",
                type: "google-ads",
                status: "pending",
                zone: "hcm",
                specialization: "string",
                created_at: 128489999,
                updated_at: 128489999,
            },
        ],
        first_page_url: "string",
        from: 0,
        last_page: 0,
        last_page_url: "string",
        links: [
            {
                url: "string",
                label: "string",
                active: "true",
            },
        ],
        next_page_url: "string",
        path: "string",
        per_page: 25,
        prev_page_url: "string",
        to: 0,
        total: 203,
    },
};

export const staff_detail = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        id: 2,
        uuid: "99efcc08-623e-ea80-847b-46c0805ac6d7",
        cid: "jYDUZqSzE3",
        display_name: "Chic Suk Yee",
        email: "chicsy@gmail.com",
        phone: "74-839-6185",
        type: "intructor",
        created_at: null,
        updated_at: 1695636583,
        contact_id: 2,
        gender: "admin",
        address: "402 Nguyễn Thị Minh Khai",
        company: "Adsplus",
        tax_code: "030406",
        fax: "215",
        bio: null,
        job_title: "Senior Intern",
        zone: "TPHCM",
        specialization: "google-ads",
        avatar_url: "",
    },
};

export const staff_courses = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: [
        {
            id: 1,
            uuid: "3254259a-6fe0-6919-d7c9-b7b43022ccb2",
            course_category_id: 6,
            name: "Nakajima Riku",
            method: "qSvQz9Vlvv",
            original_price: "480.77",
            discounted_price: "922.96",
            sale_price: "495.01",
            unit: "NVWygbX9jF",
            capacity: 8,
            enrollment: 190,
            start_date: 1695719985000,
            end_date: 1695719985000,
            start_time: 1695719985000,
            end_time: 1695719985000,
            level: "yJWlPcm2px",
            zone: "LDqSCiCpIY",
            code: "Swf0MWyljd",
            status: "bIOQRceNLe",
            stage: "WujDxdAOKh",
            description: null,
            created_at: 1134383506,
            updated_at: 1315010400,
            deleted_at: null,
            type: "facebook-ads",
        },
    ],
};

export const staff_lessions = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: [
        {
            id: 1,
            uuid: "2e1b92ba-87f3-66c6-4742-dec2e36f1913",
            course_id: 1,
            instructor_id: 1,
            topic_id: 1,
            status: "Q8PXrA6GLf",
            start_date: 1695719985000,
            end_date: 1695719985000,
            created_at: 1619552056,
            updated_at: 1220753641,
            name: "Debra Wagner",
        },
    ],
};

export const update_success = {
    status: "success",
    message: "SUCCESS",
    code: 200,
    data: {
        id: 0,
        uuid: "string",
        cid: "string",
        display_name: "NHI GIẢNG VIÊN",
        phone: "0987867564",
        email: "baobao@gmail.com",
        type: "teacher",
        status: "publish",
        zone: "hcm Chí Minh",
        specialization: "google-ads",
    },
};
